services:
  web:
    build: .
    ports:
      - "5921:5921"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_MODEL: ${OPENAI_MODEL:-gpt-4}
      OPENAI_TIMEOUT: ${OPENAI_TIMEOUT:-30}
